feature/api docs pedido
karineriquena/fiap-soat1-tech-challenge pull request #14
Opened 2023-07-05 13:59 UTC by mitestainer

Adicionando a rota de pedido na documentação do swagger.

2023-07-05 16:44 UTC, karineriquena requested changes

2023-07-05 16:44 UTC, karineriquena commented on src/adapter/driver/api/docs/paths/pedido.ts
> +        delete: {
pode remover o delete, não vamos ter ele

2023-07-05 20:50 UTC, HenriqueMitsuo commented on src/adapter/driver/api/docs/paths/pedido.ts
> +    },
Aqui teria que ser um array, não?
Nesse formato ele vai entender que é um objeto

2023-07-07 12:06 UTC, karineriquena approved these changes

2023-07-07 12:06 UTC, karineriquena commented on src/adapter/driver/api/docs/paths/pedido.ts
> +                            required: RequiredFields,
coloca o example aqui igual foi feito no de cliente

2023-07-07 14:11 UTC, merged