Feat - reestruturação das pastas e arquivos para clean architecture [Leia observações]
karineriquena/fiap-soat1-tech-challenge pull request #24
Opened 2023-08-10 12:05 UTC by CarolPinheiro

# Observações
Tem muito arquivo, mas vou tentar resumir o que principalmente precisam se atentar.
- Estrutura das pastas 
  - Estávamos seguindo a questão das camadas da hexagonal para separar nossas pastas (e eu sinceramente não me recordo se definimos se iamos dividir pelas camadas da clean architecture também, minha memória está péssima), então eu segui a do professor e qualquer coisa se vocês acharem melhor continuarmos dividindo pelas camadas só me avisar que eu troco.
- Como a maioria das coisas subiu para um primeiro nível, eu removi a configuração do path que tinhamos no tsconfig, majoritariamente porque o typescript já pegava os absolute imports e também porque por alguma razão ele não estava conseguindo usar os arquivos index pra fazer os imports.
- Renomeei em tudo que estava como repository pra gateway (até nos testes)
- E o arquivo que eu alterei para ordenar os status dos pedidos é esse daqui `src/gateways/pedidoGateway.ts`
- Algumas coisas como assertionConcern, errors e etc eu fiquei em dúvida do melhor lugar de onde salvar, então deixei em utils, mas estou aberta se tiverem alguma outra sugestão.
- Os commits estão um pouco caóticos, pq era muito arquivo e eu precisei ir commitando aos poucos.

2023-08-15 02:00 UTC, daniel-eiro commented
Ainda não consegui ver tudo, mas só tem um ponto que gostaria de acrescentar. Pelo fato deles terem pedido a ordenação como um dos requisitos de negócio, eu não sei aplicar isso direto somente no gateway seria uma boa. No fim das contas quem faz isso é o sort do Mongo (ou um ORDER BY de um SQL da vida), mas o que eu faria seria criar uma nova função no UseCase chamada getAllOrdered com o sort, e deixaria uma outra função getAll sem o sort. Assim, se em algum dia alguma outra pessoa fosse mudar o gateway ela saberá que deveria ter as duas implementações, e que o sort não está lá por acaso.

2023-08-15 20:50 UTC, CarolPinheiro commented
> Ainda não consegui ver tudo, mas só tem um ponto que gostaria de acrescentar. Pelo fato deles terem pedido a ordenação como um dos requisitos de negócio, eu não sei aplicar isso direto somente no gateway seria uma boa. No fim das contas quem faz isso é o sort do Mongo (ou um ORDER BY de um SQL da vida), mas o que eu faria seria criar uma nova função no UseCase chamada getAllOrdered com o sort, e deixaria uma outra função getAll sem o sort. Assim, se em algum dia alguma outra pessoa fosse mudar o gateway ela saberá que deveria ter as duas implementações, e que o sort não está lá por acaso.

@daniel-eiro Criei uma rota nova apenas pra buscar os pedidos de forma ordenada e removi a ordenação por status do get geral. Dá uma olhada e vê se é o que você estava pensando.

2023-08-16 01:27 UTC, karineriquena commented
Na pasta dos usecases, eu chamaria os "index.ts" de: pedidoUseCase.ts, produtoUseCase.ts e clienteUseCase.ts e usaria o index.ts de cada pasta somente para fazer: 
export * from './pedidoUseCase'
export * from './produtoUseCase'
export * from './clienteUseCase'

2023-08-16 01:30 UTC, karineriquena commented
A pasta interfaces, tem apenas as interfaces de gateways, será que vale a pena deixar dentro da pasta gateways?

2023-08-16 11:30 UTC, CarolPinheiro commented
> A pasta interfaces, tem apenas as interfaces de gateways, será que vale a pena deixar dentro da pasta gateways?

@karineriquena sobre isso, acho que eu prefiro manter isolada em interfaces, pq além das interfaces de gateways temos a de entitys e value objects. 

Entendo que deixamos a de useCase junto com os useCases, mas como a de gateway é usada fora do contexto de gateway também, acho que faz sentido isolarmos.

![Captura de Tela 2023-08-16 às 08 27 53](https://github.com/karineriquena/fiap-soat1-tech-challenge/assets/61391061/0766aba3-9615-49c5-8727-811890f4dd4c)

2023-08-16 11:48 UTC, CarolPinheiro commented
> Na pasta dos usecases, eu chamaria os "index.ts" de: pedidoUseCase.ts, produtoUseCase.ts e clienteUseCase.ts e usaria o index.ts de cada pasta somente para fazer: export * from './pedidoUseCase' export * from './produtoUseCase' export * from './clienteUseCase'

@karineriquena booa, gostei da ideia. Eu só troquei por fazer o import do useCase e do dto direto no index ts da pasta useCases. Como era só dois arquivos achei que era de boas não fazer um index ts na pasta de cada um pra ai fazer o export depois, mas dá uma olhada depois e me diz o que você acha.

2023-08-17 23:09 UTC, karineriquena approved these changes

2023-08-17 23:36 UTC, karineriquena requested changes

2023-08-17 23:36 UTC, karineriquena commented on package.json
>          "start": "node build/adapter/driver/api/index.js",
pra conseguir rodar, eu precisei alterar aqui:

```suggestion
        "start": "node build/api/index.js",
```

2023-08-20 23:12 UTC, karineriquena approved these changes

2023-08-21 13:22 UTC, merged