Feature/add new postgres gateway
karineriquena/fiap-soat1-tech-challenge pull request #35
Opened 2023-10-29 23:58 UTC by HenriqueMitsuo

2023-10-30 00:54 UTC, HenriqueMitsuo commented
Pessoal se possivel testem o compose:
- Estou com problemas para rodar o docker na minha maquina
  - Estou usando uma alternativa (Podman)
  - Então seria bom alguem com o docker rodando 100% testar o compose

- Alguns detalhes sobre a nova base:
  - Com o uso do ORM temos acesso ao processo de migrations
  - Basicamente o ORM consegue gerar as querys necessários para criar/alterar as tabelas
  - Já foi configurado no compose para rodar o generate e migrate ✔

- Seria bom zerar a collection de Pedidos local, a mudança pode quebrar com os dados antigos

2023-10-30 17:44 UTC, CarolPinheiro requested changes

2023-10-30 17:44 UTC, CarolPinheiro commented on src/gateways/clienteGateway.ts
> +            .insert(ClienteSchema)
Aqui acho que acabou passando e não puxamos o schema do que recebemos no construtor:

```suggestion
            .insert(this.clienteSchema)
```

2023-10-30 17:44 UTC, CarolPinheiro commented on src/gateways/pedidoGateway.ts
> +        console.log(results);
Só remover esse console que ficou pra trás

2023-10-31 00:20 UTC, HenriqueMitsuo commented
### Changelog:
- Atualiza `PedidoSchema` do mongo, torna cliente em campo não obrigatório
- Adiciona nova função `isUUID` em `AssertionConcern`
- Refatora função `checkout`, para lidar com os pedidos com e sem cliente relacionado
  - A regra ficou se o tiver id presente e for do formato UUID tenta realizar a busca por id
  - Se encontrar cria o pedido com o cliente
  - Caso não passe na regra ou não encontre o cliente, apenas cria o pedido

2023-10-31 00:55 UTC, karineriquena approved these changes

2023-10-31 01:23 UTC, CarolPinheiro approved these changes

2023-10-31 20:08 UTC, mitestainer approved these changes

2023-11-01 01:18 UTC, merged