Order: get all orders and update order
karineriquena/fiap-soat1-tech-challenge pull request #6
Opened 2023-06-22 00:48 UTC by karineriquena

2023-06-24 22:54 UTC, CarolPinheiro requested changes
Deixei algumas pequenas sugestões, se tiver alguma dúvida só me chamar

2023-06-24 22:54 UTC, CarolPinheiro commented on src/adapter/driven/infra/mongo/models/Pedido.ts
> +          type: String,
**suggestion:** Existe no mongoose um tipo só pra ObjectId, acho que pra segurança do banco seria interessante usarmos isso ao invés de String. O que acha?

```suggestion
          type: mongoose.Schema.Types.ObjectId,
```

Aqui um link para referência  https://mongoosejs.com/docs/schematypes.html

2023-06-24 22:54 UTC, CarolPinheiro commented on src/adapter/driven/infra/mongo/models/Pedido.ts
> +          product_id: { type: String, required: true },
**suggestion:** Mesma ideia de usar o tipo ObjectID aqui

2023-06-24 22:54 UTC, CarolPinheiro commented on src/adapter/driven/infra/mongo/repositories/pedidoRepository.ts
> +        });
**suggestion:** Como não vamos ter nenhum tipo de fila relacionada a pedido agora, acho que seria interessante retornarmos os pedidos ordenados por data de criação (considerando que por exemplo a cozinha usaria isso pra saber qual fazer primeiro), ou até mesclar a validação de data de criação com o status do pedido, pra garantir que eles fiquem agrupados.

 São só algumas ideias, mas você pode analisar qual acha que faz mais sentido kk se tiver alguma dúvida só chamar

2023-06-24 22:54 UTC, CarolPinheiro commented on src/core/application/useCases/pedido/pedido.interface.ts
> +    updatePedido(id: string, pedido: Partial<Pedido>): Promise<Pedido>;
**nitpick:** Micro detalhe, só corrigir o parâmetro do update, só pra seguir a classe

```suggestion
    updatePedido(id: string, pedido: Omit<Partial<Pedido>, "id">): Promise<Pedido>;
```

2023-06-24 22:54 UTC, CarolPinheiro commented on src/core/domain/entities/pedido.ts
> +      itens?: ItemPedido[];
**suggestion:** Como estamos declarando acima que essas propriedades são obrigatórias pra classe, acho que seria interessante manter apenas Cliente como opcional e id tbm.

2023-06-24 22:54 UTC, CarolPinheiro commented on src/core/domain/entities/pedido.ts
> +    this.itens = itens || [];
**suggestion:** Com exceção de cliente e id, será se não valeria retirarmos os valores default e utilizarmos o `assertArgumentNotEmpty` no validateEntity pra garantir que o usuário não enviou nada errado pro banco?

2023-06-24 22:54 UTC, CarolPinheiro commented on src/adapter/driven/infra/mongo/models/Pedido.ts
> +        deletedAt: { type: Date, required: false },
Acho que isso acabou se perdendo no grupo, mas notamos que ficou faltando nas nossas interfaces um campo para o cliente poder enviar detalhes sobre a personalização do pedido. Algo como um campo Observation (semelhante ao que o ifood tem), que seja uma string pra facilitar nossa vida.

Ai se conseguir adicionar seria maneiro e atualizar a entidade depois.

2023-06-25 13:55 UTC, CarolPinheiro commented on src/core/domain/repositories/pedidoRepository.interface.ts
> +    updatePedido(id: string, pédido: Partial<Pedido>): Promise<Pedido>;
Aqui acabou ficando um acento no pedido do parâmetro
```suggestion
    updatePedido(id: string, pedido: Partial<Pedido>): Promise<Pedido>;
```

2023-06-25 14:02 UTC, CarolPinheiro requested changes
Só um mini detalhe que eu peguei, e a questão dos valores default na entity

2023-06-25 18:25 UTC, HenriqueMitsuo commented on src/adapter/driven/infra/mongo/models/Pedido.ts
> +export default mongoose.model<Pedido>("Pedidos", PedidoSchema);
adicionar uma linha em branco ao final do arquivo, se repete em outros lugares

![image](https://github.com/karineriquena/fiap-soat1-tech-challenge/assets/46209283/7ac2389a-3f18-4212-9b10-3caaa32ed4e0)

2023-06-25 18:25 UTC, HenriqueMitsuo commented on src/adapter/driven/infra/mongo/repositories/pedidoRepository.ts
> +      return pedidosResult.sort((a, b) => statusOrder.indexOf(a.status) - statusOrder.indexOf(b.status));
Esse sort deve ser possivel no mongo sim, talvez tenha que ser via um aggregate, ex:
```typescript
this.pedidoModel.aggregate([
    {
        $addFields: {
            statusOrder: {
                $switch: {
                    branches: [
                        {
                            case: { $eq: ["$status", "recebido"] },
                            then: 0,
                        },
                        {
                            case: {
                                $eq: ["$status", "em_preparacao"],
                            },
                            then: 1,
                        },
                        {
                            case: { $eq: ["$status", "pronto"] },
                            then: 2,
                        },
                        {
                            case: {
                                $eq: ["$status", "finalizado"],
                            },
                            then: 3,
                        },
                    ],
                    default: 4,
                },
            },
        },
    },
    { $sort: { statusOrder: 1 } },
])
```

2023-06-25 18:25 UTC, HenriqueMitsuo commented on src/core/domain/entities/pedido.ts
Verifica se o seu editor tem o eslint/prettier configurado:
- tem bastente arquivo com problema de lint
![image](https://github.com/karineriquena/fiap-soat1-tech-challenge/assets/46209283/473b420d-a3f1-466e-a7e2-58067f2b0ad1)

2023-06-26 11:41 UTC, CarolPinheiro approved these changes

2023-06-26 22:14 UTC, HenriqueMitsuo requested changes
Ficou só alguns pontos
- só o do controller é mais importante
- os outros são mais de padronização/code quality

2023-06-26 22:14 UTC, HenriqueMitsuo commented on src/adapter/driver/api/controllers/pedido/pedidoController.ts
> +    }
Adicionar o tratamento de erro com tryCatch
Tem exemplos nos outros controllers

2023-06-26 22:14 UTC, HenriqueMitsuo commented on src/adapter/driver/api/controllers/pedido/pedidoController.ts
O arquivo pode ser index.ts mesmo, não temos outros exports dessa pasta, deixando só index fica mais limpo

2023-06-26 22:14 UTC, HenriqueMitsuo commented on src/core/application/useCases/pedido/index.ts
> +    }
non-blocking:
- quando estamos fazendo só a injeção de dependencia podemos optar por um shorthand
```suggestion
    constructor(private readonly pedidoRepository: IPedidoRepository) {}
```

2023-06-26 22:14 UTC, HenriqueMitsuo commented on src/core/domain/repositories/pedidoRepository.interface.ts
> +}
non-blocking:
- fica só o ponto que comentei dessas funções que fixam contexto desnecessário
- não é blocking, é uma mudança para melhorar a leitura do código

2023-06-27 00:54 UTC, HenriqueMitsuo approved these changes

2023-06-27 00:55 UTC, merged