Feature/add cliente implementation
karineriquena/fiap-soat1-tech-challenge pull request #7
Opened 2023-06-22 00:50 UTC by HenriqueMitsuo

2023-06-22 11:51 UTC, CarolPinheiro requested changes
Deixei algumas pequenas sugestões de alteração

2023-06-22 11:51 UTC, CarolPinheiro commented on src/adapter/driver/api/controllers/cliente/index.ts
> +            if (!email) return res.status(401).json();
**suggestion:** Como o e-mail está vindo via query string, e não é algo obrigatório ou tão claro pra rota, não seria interessante retornarmos aqui uma mensagem para o usuário explicando o problema?

2023-06-22 11:51 UTC, CarolPinheiro commented on src/adapter/driver/api/controllers/cliente/index.ts
> +            if (!cpf) return res.status(401).json();
**suggestion:** Mesma sugestão para retornarmos uma mensagem mais clara. 

E uma coisa que fiquei refletindo (não sei se aplicaria tbm pro e-mail), mas não faria sentido usarmos o CPF como pathParameter ao invés de queryString? Considerando que estamos buscando um usuário único.

2023-06-22 11:51 UTC, CarolPinheiro commented on src/core/application/useCases/user/index.ts
> +    }
**suggestion:** Questão que eu pensei aqui, não sei como vai ser a questão pra e-mail, mas CPF não poderíamos deixar repetir.

Acho que seria interessante antes de criar fazermos uma busca com o CPF e talvez o e-mail, pra garantir que a pessoa pode criar essa conta.

2023-06-22 11:51 UTC, CarolPinheiro commented on src/core/domain/base/assertionConcern.ts
> +        console.log(emailRegex.test(email));
**nitpick:** Acho que podemos remover esses consoles.

2023-06-22 11:51 UTC, CarolPinheiro commented on src/adapter/driver/api/types/cliente-request.ts
> +export interface CreateClienteRequestBody {
**nitpick:** Aqui acho que seria interessante o arquivo seguir o padrão de nomenclatura de `clienteRequest.interface.ts`

E não seria interessante mantermos o padrão de nomenclatura como ICreateClienteRequestBody?

2023-06-22 11:51 UTC, CarolPinheiro commented on src/core/application/useCases/user/cliente.useCase.ts
> +export interface IClienteUseCase {
**suggestion:** Aqui pra seguir a padronização que combinamos, seria interessante termos o nome do arquivo como cliente.interface.ts

2023-06-22 11:52 UTC, CarolPinheiro requested changes

2023-06-22 11:52 UTC, CarolPinheiro commented on src/core/application/useCases/user/cliente.useCase.ts
> +import { Cliente } from "@domain/entities/cliente";
**nitpick:** Micro detalhe, só precisamos alterar o nome dessa pasta para cliente.

2023-06-22 12:13 UTC, HenriqueMitsuo commented on src/adapter/driver/api/types/cliente-request.ts
> +export interface CreateClienteRequestBody {
ali foi por causa do conflito de nomes, não acho interessante esse padrão de nomeclatura

2023-06-22 12:22 UTC, CarolPinheiro commented on src/adapter/driver/api/types/cliente-request.ts
> +export interface CreateClienteRequestBody {
Falando pelo menos do nome do arquivo, eu colocaria ele no mínimo em camelCase, pra seguir o resto do projeto.

2023-06-22 13:01 UTC, CarolPinheiro commented on src/core/application/useCases/user/index.ts
> +import { Cliente } from "@domain/entities/cliente";
**nitpick:** Última coisa, só faltou mudar o nome da pasta pra cliente.

2023-06-24 22:14 UTC, CarolPinheiro requested changes
@HenriqueMitsuo hey, uma coisa que eu acabei notando só agora (erro meu), é que acabou faltando os testes. Acho que podemos seguir a estrutura que eu fiz em Produtos, ou se tiver alguma outra ideia seria maneiro termos isso.

2023-06-25 00:55 UTC, karineriquena requested changes

2023-06-25 00:55 UTC, karineriquena commented on src/adapter/driven/infra/mongo/models/Cliente.ts
> +            required: false,
Só fiquei na duvida pois no tech challenge fala sobre se identificar com CPF e se cadastrar com nome + email... Então como a identificação é pelo CPF, imagino que seja required = true:

"Os clientes são apresentados a uma interface de seleção na qual podem optar por se identificarem via CPF, se cadastrarem com nome, e-mail ou não se identificar"

O que eu imaginei: Uma tela com as duas opções "Se identificar" e "Pular e selecionar combo", sendo a opção para identificar por CPF, caso o CPF exista, traz o nome e -mail preenchidos, caso não, a pessoa preenche o nome e email.

Outra opção possível que eu imaginei seria a identificação ocorrer por "CPF" ou "E-MAIL" que são as opções que não se repetiriam numa base de dados

2023-06-25 00:55 UTC, karineriquena commented on src/adapter/driver/api/routes/clienteRouter.ts
> +    );
sugestão (pode ignorar se quiser):
```suggestion
    );
   
```

2023-06-25 00:55 UTC, karineriquena commented on src/adapter/driver/api/routes/clienteRouter.ts
> +    );
```suggestion
    );
    
```

2023-06-25 00:55 UTC, karineriquena commented on src/adapter/driver/api/routes/index.ts
> +    serverRouter.use("/cliente", makeClienteRouter());
a rota de produto está no plural e a de cliente no singular, deveríamos padronizar?

2023-06-25 00:55 UTC, karineriquena commented on src/adapter/driver/api/types/clienteRequest.ts
> +export interface CreateClienteRequestBody {
vamos seguir com o ".interface" no nome do arquivo?

clientRequest.interface.ts

2023-06-25 00:55 UTC, karineriquena commented on src/core/application/useCases/user/index.ts
> +import { Cliente } from "@domain/entities/cliente";
o que é nitpick? curiosidade só rs

2023-06-25 00:55 UTC, karineriquena commented on src/core/application/useCases/user/index.ts
> +        const jaExiste = await this.clienteRepository.verificarDuplicado({
```suggestion
        const alreadyExists= await this.clienteRepository.verificarDuplicado({
```

2023-06-25 00:55 UTC, karineriquena commented on src/core/domain/base/valueObject.ts
> +        if (valueObject.props === undefined) {
precisa do "=== undefined"?  ou pode ser:

```typescript
if (valueObject.props) {
```

2023-06-25 13:44 UTC, HenriqueMitsuo commented on src/adapter/driven/infra/mongo/models/Cliente.ts
> +            required: false,
acho que faz sentido, tinha interpretado que era um cpf opcional

2023-06-25 13:46 UTC, HenriqueMitsuo commented on src/adapter/driver/api/routes/index.ts
> +    serverRouter.use("/cliente", makeClienteRouter());
vou trocar a de "produtos", o correto é singular para rest

2023-06-25 13:47 UTC, CarolPinheiro commented on src/core/application/useCases/user/index.ts
> +import { Cliente } from "@domain/entities/cliente";
@karineriquena nitpick é tipo, um micro detalhe kkk como mudar nome de pasta, etc

2023-06-25 14:03 UTC, HenriqueMitsuo commented on src/adapter/driver/api/types/clienteRequest.ts
> +export interface CreateClienteRequestBody {
Precisaria mesmo? não entendi muito bem a utilidade de colocar interface no nome do arquivo, a impressão é que isso resolve um problema muito simples talvez no inicio de um projeto, quando não se tem contexto da estrutura e/ou typescript, isso vem de algum guia? do que já vi acho que era alguma convensão do angular
- o arquivo já está em uma pasta types

2023-06-25 21:31 UTC, karineriquena commented on src/adapter/driver/api/types/clienteRequest.ts
> +export interface CreateClienteRequestBody {
é que a gente colocou ".interface" em outros... e sim acho que é do angular colocar .interface, .module, .service etc... mas vou fechar aqui então

2023-06-25 21:33 UTC, karineriquena approved these changes

2023-06-25 21:38 UTC, CarolPinheiro approved these changes

2023-06-25 23:47 UTC, daniel-eiro commented
Boa Henrique, dei uma olhada nos códigos e ficou muito bom. Eu ia comentar sobre os retornos dos status code (tinha um 401 ali que eu não estava entendendo muito bem), mas vi que você alterou para um arquivo padronizado, muito bacana, parabéns!

2023-06-26 12:04 UTC, merged