Feature/add health check
karineriquena/fiap-soat1-tech-challenge pull request #9
Opened 2023-06-25 14:08 UTC by daniel-eiro

- Criei em cima do branch do Henrique, que tinha umas coisas a mais que usei como base para o meu
- Criei a rota e controller, não vi necessidade de um use case para esse cenário então não criei
- Eu notei um comportamento estranho no Mongoose que não retorna um erro de conexão logo quando a aplicação boota
- Para testar: Dar um stop no Container do Mongo, mas como eu disse acima é bom esperar uns segundos para não receber um falso positivo

2023-06-25 17:09 UTC, HenriqueMitsuo requested changes
@daniel-eiro depois realiza um merge ou rebase com base na branch 
- #7

2023-06-25 17:09 UTC, HenriqueMitsuo commented on src/adapter/driver/api/controllers/health/healthController.ts
> +}
Dúvida:
- A resposta poderia ser mais completa? tipo um objeto com serviços, bancos, etc, ex:
```typescript
{
  "server": "healthy",
  "mongo": "healthy",
}
```
- um ponto opcional seria mudar para uma resposta em json

2023-06-25 17:09 UTC, HenriqueMitsuo commented on src/adapter/driver/api/controllers/health/healthController.ts
> +import testConnection from "../../../../driven/infra/mongo/helpers/testConnection";
- dar preferencia para o alias
```suggestion
import testConnection from "@infra/mongo/helpers/testConnection";
```

2023-06-25 17:09 UTC, HenriqueMitsuo commented on src/adapter/driven/infra/mongo/helpers/testConnection.ts
> +export default async function testConnection(): Promise<boolean> {
2 pontos:
- seria bom trocar para um named export
- utilizar um nome mais especifico, ex: `testMongoConnection`

2023-06-25 23:35 UTC, daniel-eiro commented on src/adapter/driver/api/controllers/health/healthController.ts
> +}
Nesse caso eu entendo que é uma rota a ser usada para um Load Balancer, por exemplo. No geral quem olha isso está mais preocupado com os Status Codes retornados do que as mensagem em si (uma vez que essa mensagem pode variar bastante de aplicação para aplicação).

- No meu entendimento a resposta é binária, ou o sistema está 100% saudável, ou não está. No nosso caso, só temos a dependência da aplicação em si e do Mongo. Se o Mongo estiver fora o código irá verificar, se a aplicação estiver fora, a rota nem vai responder (porque ela mesmo faz parte da aplicação).

- Isso que você sugeriu faz sentido sim, mas aí vejo mais para uma ferramenta externa de Monitoramento e Observabilidade, que não está no nosso escopo agora

2023-06-25 23:37 UTC, daniel-eiro commented on src/adapter/driver/api/controllers/health/healthController.ts
> +import testConnection from "../../../../driven/infra/mongo/helpers/testConnection";
Boa, não conhecia essa funcionalidade do alias

2023-06-25 23:38 UTC, daniel-eiro commented on src/adapter/driven/infra/mongo/helpers/testConnection.ts
> +export default async function testConnection(): Promise<boolean> {
Me desculpa a ignorância, o que seria essa troca para named export?

2023-06-26 01:17 UTC, HenriqueMitsuo commented on src/adapter/driven/infra/mongo/helpers/testConnection.ts
> +export default async function testConnection(): Promise<boolean> {
Sobre o nome não precisa ser genérico, pq ele está exatamente na pasta do mongo, tudo que está ai é do contexto dele
- por isso que o ideal é que seja `testMongoConnection`

No javascript/typescript quando utilizamos modulos, tem duas formas de exportar algo de um arquivo
- default export
  - ex: `export default function testConnection`
  - só pode ter 1 por arquivo
  - quem faz o import pode colocar qualquer nome
  - pode dificultar em projetos grandes
- named export
  - ex: `export const function testConnection`
  - em um arquivo pode N named exports
  - quem faz o import pega exatamente o que foi exportado

2023-06-27 01:37 UTC, HenriqueMitsuo approved these changes

2023-06-27 01:37 UTC, HenriqueMitsuo commented on src/adapter/driven/infra/mongo/helpers/testMongoConnection.ts
> +export async function testConnection(): Promise<boolean> {
acho que só faltou renomear a função

2023-06-27 01:52 UTC, daniel-eiro commented on src/adapter/driven/infra/mongo/helpers/testMongoConnection.ts
> +export async function testConnection(): Promise<boolean> {
Ok, faltou mudou msm. Mudei aqui

2023-06-27 01:55 UTC, merged